networks:
  loan-issuer-network:
    driver: bridge

services:

  ms-calculator:
    build:
      context: .
      dockerfile: MS-Calculator/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - loan-issuer-network

  loan-issuer-database:
    build:
      context: .
      dockerfile: MS-Deal/database.Dockerfile
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - loan-issuer-network
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./Documents/pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - loan-issuer-network
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    networks:
      - loan-issuer-network
    ports:
      - "${KAFKA_PORT}:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ms-deal:
    build:
      context: .
      dockerfile: MS-Deal/Dockerfile
    networks:
      - loan-issuer-network
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - loan-issuer-database

  ms-dossier:
    build:
      context: .
      dockerfile: MS-Dossier/Dockerfile
    networks:
      - loan-issuer-network
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    volumes:
      - ./Documents/Dossier:/home/application/ms-dossier/documents

  ms-statement:
    build:
      context: .
      dockerfile: MS-Statement/Dockerfile
    networks:
      - loan-issuer-network
    ports:
      - "8082:8082"

  ms-gateway:
    build:
      context: .
      dockerfile: MS-Gateway/Dockerfile
    networks:
      - loan-issuer-network
    ports:
      - "8084:8084"